config/routes.rb
Plusdollar::Application.routes.draw do
  devise_for :users

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :sexes

  resources :genders

  resources :newusers

  root :to => "newusers#index"
  resources :users

  resources :attendances

  resources :posts
  resources :pledges

end

app/models/sex.rb
class Sex < ActiveRecord::Base
end

app/controllers/sexes_controller.rb
class SexesController < ApplicationController
  # GET /sexes
  # GET /sexes.json
  def index
    @sexes = Sex.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sexes }
    end
  end

  # GET /sexes/1
  # GET /sexes/1.json
  def show
    @sex = Sex.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sex }
    end
  end

  # GET /sexes/new
  # GET /sexes/new.json
  def new
    @sex = Sex.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sex }
    end
  end

  # GET /sexes/1/edit
  def edit
    @sex = Sex.find(params[:id])
  end

  # POST /sexes
  # POST /sexes.json
  def create
    @sex = Sex.new(params[:sex])

    respond_to do |format|
      if @sex.save
        format.html { redirect_to @sex, notice: 'Sex was successfully created.' }
        format.json { render json: @sex, status: :created, location: @sex }
      else
        format.html { render action: "new" }
        format.json { render json: @sex.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sexes/1
  # PUT /sexes/1.json
  def update
    @sex = Sex.find(params[:id])

    respond_to do |format|
      if @sex.update_attributes(params[:sex])
        format.html { redirect_to @sex, notice: 'Sex was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sex.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sexes/1
  # DELETE /sexes/1.json
  def destroy
    @sex = Sex.find(params[:id])
    @sex.destroy

    respond_to do |format|
      format.html { redirect_to sexes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/sexes_helper.rb
module SexesHelper
end

app/views/sexes/_form.html.erb
<%= form_for(@sex, html: {class: "form-horizontal"}) do |f| %>
  <% if @sex.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sex.errors.count, "error") %> prohibited this sex from being saved:</h2>

      <ul>
      <% @sex.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :gender, class: 'control-label' %>
    <div class="controls">
    	<%= f.text_field :gender %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
  

<% end %>

app/views/sexes/edit.html.erb
<h1>Editing sex</h1>

<%= render 'form' %>

<%= link_to 'Show', @sex %> |
<%= link_to 'Back', sexes_path %>

app/views/sexes/index.html.erb
<h1>Listing sexes</h1>

<table>
  <tr>
    <th>Gender</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sexes.each do |sex| %>
  <tr>
    <td><%= sex.gender %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Sex', new_sex_path %>

app/views/sexes/new.html.erb
<h1>New Gender</h1>

<%= render 'form' %>

<%= link_to 'Back', newusers_path %>

app/views/sexes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Gender:</b>
  <%= @sex.gender %>
</p>


<%= link_to 'Edit', edit_sex_path(@sex) %> |
<%= link_to 'Back', newusers_path %>